// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSPNlHEsWee8f8wE03IyJJEAxzTyVWQ1E',
    appId: '1:255449229119:web:880bb35c215bfe7d90d58a',
    messagingSenderId: '255449229119',
    projectId: 'fir-memo-app-f6afe',
    authDomain: 'fir-memo-app-f6afe.firebaseapp.com',
    storageBucket: 'fir-memo-app-f6afe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUMjxRYUMDM8dL8RpTvBtgD8fkpZTyaVo',
    appId: '1:255449229119:android:78b6f3773142c12190d58a',
    messagingSenderId: '255449229119',
    projectId: 'fir-memo-app-f6afe',
    storageBucket: 'fir-memo-app-f6afe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFpY8LKseLEQdiG3E3AhndnVYe8iE7z4g',
    appId: '1:255449229119:ios:2f2fe7fc392d49c790d58a',
    messagingSenderId: '255449229119',
    projectId: 'fir-memo-app-f6afe',
    storageBucket: 'fir-memo-app-f6afe.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFpY8LKseLEQdiG3E3AhndnVYe8iE7z4g',
    appId: '1:255449229119:ios:5886b6fc598d3d7c90d58a',
    messagingSenderId: '255449229119',
    projectId: 'fir-memo-app-f6afe',
    storageBucket: 'fir-memo-app-f6afe.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseApp.RunnerTests',
  );
}
